      revenuecat:
        patterns:
          - "com.revenuecat.purchases*"
      datastore:
        patterns:
          - "androidx.datastore*"
      credentials:
        patterns:
          - "androidx.credentials*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "12:20"
      timezone: "Europe/Madrid"
    labels:
      - "dependencies"
      - "github-actions"
    assignees:
      - "Cabero52"
    commit-message:
      prefix: "ci"
    groups:
      github-actions:
        patterns:
          - "*"
